### PR TITLE
harry potter Movie Details list

### PR DESCRIPTION
**Pull request by Jitendra0527**

### CODE REVIEW

**Comment by Jitendra0527** [comment]
Yes it completed I can move to main branch or not?

**Comment by Jitendra0527** [comment]
I am created one branch is created is develop

**Comment by alcfeoh** [comment]
Please use your own Github repo. We don't want your code to be public here.

*Alain Chautard*
Google Developer Expert in Angular *
*
Consultant and trainer at angulartraining.com ( http://angulartraining.com ) - Interstate 21, LLC

***@***.***
www.interstate21.com ( http://www.interstate21.com )
Rancho Cordova, California, USA

**Comment by Jitendra0527** [comment]
Ok, thank you.

**Pull request closed without merging**
